#ifndef DEBUGGING_FLAGS_H
#define DEBUGGING_FLAGS_H

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_ENABLE_LOCATION_SOURCE() (false)
#define BUILDFLAG_INTERNAL_ENABLE_PROFILING() (false)
#define BUILDFLAG_INTERNAL_CAN_UNWIND_WITH_FRAME_POINTERS() (false)
#define BUILDFLAG_INTERNAL_UNSAFE_DEVELOPER_BUILD() (false)

#endif
